### ISSUE TITLE
Create separate optical tracker plugin for vrep

### ISSUE THREAD

**Issue by astrick3** [ahundt/robone#23]
- [ ] How much can we modify in real time via the C API?
- [ ] integrate with main arm commanding loop in vrep
- [ ] so bone is moved
- [ ] arm optical tracker position is read
originally titled: Integrate optical tracking data into cut file and arm commanding loops

**Comment by ahundt** [comment]
This issue was moved to ahundt/grl#23
